package model.pojo;
// Generated 26/12/2014 08:58:27 PM by Hibernate Tools 4.3.1



/**
 * Thanhvien generated by hbm2java
 */
public class Thanhvien  implements java.io.Serializable {


     private Integer id;
     private String tenDn;
     private String mathKhau;

    public Thanhvien() {
    }

    public Thanhvien(String tenDn, String mathKhau) {
       this.tenDn = tenDn;
       this.mathKhau = mathKhau;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenDn() {
        return this.tenDn;
    }
    
    public void setTenDn(String tenDn) {
        this.tenDn = tenDn;
    }
    public String getMathKhau() {
        return this.mathKhau;
    }
    
    public void setMathKhau(String mathKhau) {
        this.mathKhau = mathKhau;
    }




}


